name: smarthome
description: 'A new Flutter project.'
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^5.0.0
  flutter_speed_dial: ^7.0.0
  fluttertoast: ^8.2.2
  connectivity_plus: ^4.0.1
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^14.0.0
  permission_handler: ^10.4.2
  googleapis: ^11.2.0
  googleapis_auth: ^1.4.1
  google_sign_in: ^5.2.1
  percent_indicator: ^4.2.3
  http: ^1.1.0
  flutter_circle_color_picker: ^0.3.0
  carousel_slider: ^4.2.1
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  mqtt_client: ^10.2.0
  provider: ^6.1.2
  flutter_3d_controller: ^1.2.1
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
